controller_list:
  - name: fake_bot_mh5l_controller
    type: $(arg execution_type)
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
  - name: fake_bot_mh5l_pgn64_controller
    type: $(arg execution_type)
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
initial:  # Define initial robot poses.
  - group: bot_mh5l
    pose: all-zeros
  - group: bot_mh5l_pgn64
    pose: all-zeros